### ISSUE TITLE
Express.js and connect-mongo session “TypeError: Cannot read property 'upserted' of undefined”

### ISSUE THREAD

**Issue by melnikovkolya** [kcbanner/connect-mongo#230]
I am trying to store sessions, however I get the following Error:

    TypeError: Cannot read property 'upserted' of undefined

The usage of `connect-mongo` looks as follows:

    import session from 'express-session';
    const MongoStore = require('connect-mongo')(session);
    
    app.use(session({
      secret: 'SECRET',
      store: new MongoStore({ url: 'mongodb://mongo:27017/sessions' }),
      saveUninitialized: true,
      resave: false
    }));

I also tried using: `mongooseConnection = mongoose.connections[0]` and still the same error.

At the same time, I can see that session entries are being created on every page reload with the following contents:

    {
      "_id": "zO68C8OuARTUblw3EqHfUikR_IIHRaQq",
      "session": "{\"cookie\": \"originalMaxAge\":null,\"expires\":null,\"httpOnly\":true,\"path\":\"/\"    }}",
      "expires": new Date(1470779765287)
    }

And the expiration date is set to 14 days from the creation timestamp (default value)

Package versions used:

    "cookie-parser": "^1.4.3",
    "connect-mongo": "^1.3.1",
    "express": "~4.0.0",
    "express-session": "^1.14.0",

Mongo v3.2.4

**Comment by jdesboeufs** [comment]
It had been fixed in `1.3.2`.
See #228 ;)
Le jeu. 28 juil. 2016 à 23:51, nik mel-nik-ov <notifications@github.com> a
écrit :

**Comment by melnikovkolya** [comment]
Hey, thanks for an immediate reply. Just bumped it to 1.3.2 and voila! :)

Muchas gracias!

**Comment by natizlp** [comment]
I am still getting this issue in 1.3.2?

```
TypeError: Cannot read property 'upserted' of undefined
    at .../node_modules/connect-mongo/src/index.js:252:36
```
The content of responseArray seems to be: ```[ { ok: 1, nModified: 1, n: 1 } ]```

```
    "mongojs": "~2.4.0",
    "connect-mongo": "~1.3.2",
```

```
brew info mongodb
mongodb: stable 3.2.0 (bottled)
```
